### PR TITLE
Ref #36 -- Add time of day as additional instruction

### PR DESCRIPTION
**Pull request by mostafa-anm**

### CODE REVIEW

**Review by herrbenesch — APPROVED** [review]
image

**Comment by herrbenesch** [comment]
@mostafa-anm is there a test yet for the system prompt? you might created/update it.

**Review by codingjoe — CHANGES_REQUESTED** [review]
Please use zoneinfo. Again Python 3.12 ;)

**Comment by codingjoe** [comment]
You can simply use `sam.config.TIMEZONE`. It'll have what you need.

**Review by codingjoe — APPROVED** [review]

**Pull request merged**
